[package]
name = "mini-internal"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-core = { path = "../mini-core" }
mini-window = { path = "../mini-window" }
mini-resource = { path = "../mini-resource" }
mini-engine = { path = "../mini-engine" }
mini-winit = { path = "../mini-winit" }
