[package]
name = "mini-task"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-core = { path = "../mini-core" }

num-traits = "0.2.14"
parking_lot = "0.12.0"
futures = { version = "0.3.17", features = ["thread-pool"] }
