[package]
name = "mini-resource"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-core = { path = "../mini-core" }
mini-task = { path = "../mini-task" }

mini-resource-macros = { path = "macros" }

thiserror = { workspace = true }
