[package]
name = "mini-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { version = "22.0" }
mini-core = { path = "../mini-core" }
mini-window = { path = "../mini-window" }
mini-resource = { path = "../mini-resource" }
image = { version = "0.25" }
naga_oil = "0.14"
